// Run against tests/iris-synaxis.fixture.mjs. All IO is local synthetic data.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const screenshots=mkdtempSync(join(tmpdir(),'iris-synaxis-ui-'));
process.env.IRIS_SYNAXIS_FIXTURE_PORT='3009';
const {server}=await import('./iris-synaxis.fixture.mjs');
const {chromium}=createRequire(process.argv[2])('playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:390,height:1050}}),errors=[];
page.setDefaultTimeout(8000);
page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message);});
page.on('dialog',d=>d.accept());
const go=async(query='')=>{await page.goto('http://127.0.0.1:3009/'+query);await page.getByRole('button',{name:'시낙시스',exact:true}).click();await page.getByRole('button',{name:'다시 조회',exact:true}).waitFor();await page.waitForFunction(()=>window.fixture.reads.includes('parties'));};
const fit=async(label)=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' horizontal overflow');
  const clipped=await page.evaluate(()=>Array.from(document.querySelectorAll('button')).filter(e=>e.getClientRects().length&&!e.closest('[hidden]')&&e.textContent.trim().length>2&&e.scrollWidth>e.clientWidth+2).map(e=>e.textContent.trim()));
  assert.deepEqual(clipped,[],label+' clipped button text');
};
try{
  await go();await page.getByRole('button',{name:'길드버스 생성',exact:true}).waitFor();
  await page.getByRole('button',{name:'스마트 파티 매칭',exact:true}).click();
  await page.locator('.iris-synaxis-matching').getByRole('button',{name:/열두글자닉네임테스트용/}).click();
  await page.getByRole('region',{name:'열두글자닉네임테스트용 레이드·어비스 완료 상태'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'타인캐릭터',exact:true}).count(),0);
  const dates=page.locator('.iris-synaxis-matching button').filter({hasText:/\d{2}-\d{2}/});
  console.log('Matching actual React own selection/completion PASS');
  await dates.first().click();await page.getByRole('dialog').waitFor();
  assert.ok(await page.getByText('출발 희망 일시 설정',{exact:true}).count());
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('[role=dialog]').contains(document.activeElement)),true);
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
  await page.getByRole('button',{name:'길드버스 생성',exact:true}).click();await page.getByRole('dialog',{name:'길드 버스 개설',exact:true}).waitFor();
  await fit('create modal');
  await page.getByRole('dialog',{name:'길드 버스 개설',exact:true}).getByText(/26-\d{2}-\d{2}/).click();
  await page.getByRole('button',{name:'2026년',exact:true}).click();await page.getByText('연도 선택',{exact:true}).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByText('출발 희망 일시 설정',{exact:true}).isVisible(),true,'Escape closes only the year picker');
  assert.equal(await page.getByText('연도 선택',{exact:true}).count(),0);
  await page.keyboard.press('Escape');await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'길드버스',exact:true}).click();
  console.log('Bus card buttons',await page.locator('[class*="busCard"] button').allTextContents());
  await page.getByRole('button',{name:/버스 수정/}).click();await page.getByRole('dialog',{name:'길드 버스 수정',exact:true}).waitFor();
  await page.screenshot({path:join(screenshots,'390-edit.png')});
  await fit('edit modal');
  await page.evaluate(()=>window.fixture.setShown(false));await page.waitForTimeout(50);
  assert.equal(await page.getByRole('dialog',{name:'길드 버스 수정',exact:true,includeHidden:true}).isVisible(),false,'inactive portal must not cover native closing UI');
  await page.evaluate(()=>window.fixture.setShown(true));await page.getByRole('dialog',{name:'길드 버스 수정',exact:true}).waitFor();
  await page.getByRole('button',{name:'목표 컨텐츠 선택',exact:true}).click();await page.getByText('에이렐',{exact:true}).click();await page.getByRole('button',{name:'적용하기',exact:true}).click();
  await page.getByRole('dialog',{name:'길드 버스 수정',exact:true}).getByRole('textbox').fill('변경한 공지');
  await page.getByRole('button',{name:/다음: 캐릭터 선택/}).click();await page.getByRole('button',{name:/수정 저장 · 재편성/}).click();
  await page.waitForFunction(()=>window.fixture.writes.length===1);await page.getByRole('dialog',{name:'길드 버스 수정',exact:true}).waitFor({state:'detached'});
  const edit=await page.evaluate(()=>window.fixture.writes[0]);assert.equal(edit.body.expectedAccountId,'fixture-account');assert.equal(edit.body.payload._busSettings.contentId,'raid_eirel');assert.equal(edit.body.payload._busSettings.memo,'변경한 공지');
  console.log('Actual bus edit Cabrak→Eirel/scoped submit/draft preserved on hide PASS');
  const before=await page.evaluate(()=>window.fixture.reads.length);
  await page.getByRole('button',{name:'크로노스',exact:true}).click();
  await page.evaluate(()=>window.fixture.emit('INSERT',{...window.fixture.tables.parties[0],id:33,memo:'새 일반 파티'}));
  await page.getByRole('status',{name:'새 파티 또는 길드버스'}).waitFor();
  await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.fixture.reads.length),before,'no hidden reads');
  await page.getByRole('button',{name:/시낙시스/}).click();await page.getByRole('button',{name:/일반 파티/}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[class*="cardContainer"]').length===2);
  assert.equal(await page.getByRole('status',{name:'새 파티 또는 길드버스'}).count(),0);
  await page.evaluate(()=>window.fixture.emit('INSERT',{...window.fixture.tables.parties[1],id:34,memo:'새 버스'}));
  await page.getByRole('status',{name:'새 길드버스 1개'}).waitFor();
  await page.locator('.iris-synaxis-tabs').getByRole('button',{name:/길드버스/}).click();
  await page.getByText('새 버스',{exact:true}).waitFor();console.log('Realtime auto refresh/hidden dots/acknowledgment PASS');
  await page.goto('http://127.0.0.1:3009/');await page.waitForFunction(()=>window.fixture.channels.length===1);
  await page.evaluate(()=>window.fixture.emit('INSERT',{...window.fixture.tables.parties[0],id:35}));await page.getByRole('status',{name:'새 파티 또는 길드버스'}).waitFor();
  assert.equal(await page.evaluate(()=>window.fixture.reads.length),0);
  await page.getByRole('button',{name:/^시낙시스/}).click();await page.waitForFunction(()=>document.querySelectorAll('[class*="cardContainer"]').length===2);
  assert.equal(await page.getByRole('status',{name:'새 파티 또는 길드버스'}).count(),0,'default list acknowledges fresh rows on first open');
  for(const width of [320,390,768,1280])for(const font of width>=768?[18,20,22]:[18]){
    await page.setViewportSize({width,height:1050});await go('?font='+font);
    await fit('list '+width+'/'+font);
    await page.getByRole('button',{name:'스마트 파티 매칭',exact:true}).click();await fit('matching '+width+'/'+font);
    if(width===320)await page.screenshot({path:join(screenshots,'320-matching.png')});
    await page.getByRole('button',{name:'길드버스 생성',exact:true}).click();await page.getByRole('dialog').waitFor();await fit('bus modal '+width+'/'+font);await page.keyboard.press('Escape');
  }
  await go('?member=1');assert.equal(await page.getByRole('button',{name:'길드버스 생성',exact:true}).count(),0);
  await page.getByRole('button',{name:'길드버스',exact:true}).click();assert.equal(await page.getByRole('button',{name:/버스 수정|관리자 인계|해산/}).count(),0);
  await page.getByRole('button',{name:'일반 파티',exact:true}).click();await page.getByRole('button',{name:'신청',exact:true}).click();
  await page.getByRole('radio',{name:'열두글자닉네임테스트용 참가 선택',exact:true}).check();
  await page.getByRole('button',{name:'열두글자닉네임테스트용 완료 상태 보기',exact:true}).click();
  await page.getByRole('region',{name:'열두글자닉네임테스트용 레이드·어비스 완료 상태',exact:true}).waitFor();
  assert.equal(await page.getByRole('radio',{name:'타인캐릭터 참가 선택',exact:true}).count(),0);
  await page.getByRole('button',{name:/파티 참가!/}).click();
  await page.waitForFunction(()=>window.fixture.writes.length===1);
  const joinRequest=await page.evaluate(()=>window.fixture.writes[0]);assert.equal(joinRequest.body.expectedAccountId,'fixture-account');assert.ok(joinRequest.body.payload.members.some(m=>m.name==='열두글자닉네임테스트용'));
  await page.getByRole('button',{name:'스마트 파티 매칭',exact:true}).click();
  await page.getByRole('button',{name:/파티 매칭 등록하기/}).click();
  await page.waitForFunction(()=>window.fixture.writes.length===2);
  const matching=await page.evaluate(()=>window.fixture.writes[1]);assert.equal(matching.body.expectedAccountId,'fixture-account');assert.equal(matching.body.action,'insert');assert.ok(matching.body.payload.members.every(m=>['내첫캐릭터','열두글자닉네임테스트용'].includes(m.name)));
  console.log('Actual join + matching submit/scoped HTTP/owned selections PASS');
  assert.deepEqual(errors,[]);console.log('Responsive 4 widths + PC 3 font sizes/member permissions/pageerror0 PASS');
  console.log('Screenshots '+screenshots);
}catch(error){console.error('DOM',await page.locator('body').innerText());throw error;}finally{await browser.close();server.close();}
