import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {loadTS} from './load-ts.mjs';
function api(){assert.ok(existsSync('lib/irisAppearance.ts'),'Missing validated local appearance preferences');return loadTS('lib/irisAppearance.ts');}
function storage(){const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),values};}
test('theme survives reload and is isolated by environment',()=>{const a=api(),s=storage();assert.equal(a.writeTheme(s,'development','lumen'),true);assert.equal(a.readAppearance(s,'development','a').theme,'lumen');assert.equal(a.readAppearance(s,'production','a').theme,'aureum');});
test('contrast reports indistinguishable colors, clear colors, and invalid input safely',()=>{const a=api();assert.equal(typeof a.currencyColorContrast,'function');assert.equal(a.currencyColorContrast('#ffffff','#ffffff'),1);assert.equal(a.currencyColorContrast('#000000','#ffffff'),21);assert.equal(a.currencyColorContrast('url(x)','#ffffff'),null);});
test('currency emphasis is account-local and never stores balances',()=>{const a=api(),s=storage();a.writeCurrencyEmphasis(s,'development','a',{'골드':{color:'#ab12CD',bold:true,italic:true}});assert.deepEqual(a.readAppearance(s,'development','a').emphasis['골드'],{color:'#ab12CD',bold:true,italic:true});assert.deepEqual(Object.keys(a.readAppearance(s,'development','b').emphasis),[]);assert.ok([...s.values.values()].every(v=>!v.includes('amount')&&!v.includes('observedAt')));});
test('unsafe colors, extra fields, invalid booleans, huge maps and invalid names are rejected',()=>{const a=api();for(const value of [{'골드':{color:'url(x)',bold:true,italic:false}},{'골드':{color:null,bold:'yes',italic:false}},{'골드':{color:null,bold:false,italic:false,amount:1}},{'':{color:null,bold:false,italic:false}},Object.fromEntries(Array.from({length:201},(_,i)=>[String(i),{color:null,bold:false,italic:false}]))])assert.throws(()=>a.parseCurrencyEmphasis(value));});
test('prototype-like currency names remain own data, without prototype mutation',()=>{const a=api(),value=a.parseCurrencyEmphasis(JSON.parse('{"__proto__":{"color":null,"bold":true,"italic":false}}'));assert.equal(Object.hasOwn(value,'__proto__'),true);assert.equal(value.__proto__.bold,true);assert.equal({}.bold,undefined);});
test('blocked or damaged storage has a safe session-only fallback without overwriting it',()=>{const a=api(),broken={getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}};assert.equal(a.readAppearance(broken,'development','a').persistent,false);assert.equal(a.writeTheme(broken,'development','lumen'),false);const s=storage();a.writeCurrencyEmphasis(s,'development','a',{});const key=[...s.values.keys()][0];s.values.set(key,'x'.repeat(32769));assert.equal(a.readAppearance(s,'development','a').persistent,false);assert.equal(s.values.get(key).length,32769);});
