-- KRONOS expansion. Apply manually after a backup. Existing catalogs and data are preserved.
-- New private tables are accessed only through session-checked server APIs.
begin;
create table if not exists public.kronos_shop_items (
  id bigint generated by default as identity primary key,
  map text not null, npc text not null, reward text not null,
  reward_cnt integer not null default 1 check (reward_cnt > 0),
  cost_cnt integer not null default 1 check (cost_cnt >= 0),
  "limit" integer not null default 1 check ("limit" between 1 and 9999),
  reset_type text not null default '주간' check (reset_type in ('일간', '주간')),
  scope text not null default '캐릭당' check (scope in ('캐릭당', '계정당')),
  is_active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.kronos_missions (
  id bigint generated by default as identity primary key,
  town text not null check (town in ('티르코네일','던바튼','콜헨','반호르','이멘마하')),
  title text not null, description text not null default '',
  max_count integer not null default 3 check (max_count between 1 and 9999),
  rewards jsonb not null default '[]'::jsonb check (jsonb_typeof(rewards) = 'array' and jsonb_array_length(rewards) between 1 and 6),
  is_active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.kronos_progress (
  account_id uuid not null references public.accounts(id) on delete cascade,
  character_name text references public.characters(nickname) on update cascade on delete cascade,
  target_key text generated always as (coalesce(character_name, '')) stored,
  kind text not null check (kind in ('shop','mission')), item_id bigint not null,
  period_start timestamptz not null, count integer not null default 0 check (count >= 0),
  bookmarked boolean not null default false,
  primary key (account_id, target_key, kind, item_id)
);
create table if not exists public.kronos_reminders (
  account_id uuid not null references public.accounts(id) on delete cascade,
  character_name text not null references public.characters(nickname) on update cascade on delete cascade,
  slot integer not null check (slot in (0,1)),
  title text not null default '' check (length(title) <= 100),
  content text not null default '' check (length(content) <= 10000),
  color text not null default 'theme' check (color in ('theme','cream','mint','rose','blue')),
  font text not null default 'sans' check (font in ('sans','serif','mono')),
  font_size numeric not null default 0.85 check (font_size between 0.7 and 1.2),
  updated_at timestamptz not null default now(), primary key (account_id, character_name, slot)
);
alter table public.kronos_shop_items enable row level security;
alter table public.kronos_missions enable row level security;
alter table public.kronos_progress enable row level security;
alter table public.kronos_reminders enable row level security;
revoke all on public.kronos_shop_items, public.kronos_missions, public.kronos_progress, public.kronos_reminders from public, anon, authenticated;
grant all on public.kronos_shop_items, public.kronos_missions, public.kronos_progress, public.kronos_reminders to service_role;
revoke all on sequence public.kronos_shop_items_id_seq, public.kronos_missions_id_seq from public, anon, authenticated;
grant usage, select on sequence public.kronos_shop_items_id_seq, public.kronos_missions_id_seq to service_role;

-- Atomic increment and reset: simultaneous tabs cannot overwrite a newer count.
create or replace function public.sanctum_kronos_progress(p_account uuid, p_character text, p_kind text, p_item bigint, p_delta integer, p_bookmarked boolean default null)
returns setof public.kronos_progress language plpgsql security definer
set search_path = pg_catalog, public as $$
declare v_max integer; v_cycle text := '주간'; v_scope text := '캐릭당'; v_character text := p_character; v_period timestamptz;
begin
  if p_delta not in (-1,0,1) or not exists (
    select 1 from public.characters c join public.accounts a on a.nickname = c.owner
    where a.id = p_account and c.nickname = p_character
  ) then raise exception '캐릭터 수정 권한이 없습니다.'; end if;
  if p_kind = 'shop' then
    select s."limit", s.reset_type, s.scope into v_max, v_cycle, v_scope from public.kronos_shop_items s where s.id = p_item and s.is_active;
  elsif p_kind = 'mission' then
    select m.max_count into v_max from public.kronos_missions m where m.id = p_item and m.is_active;
  end if;
  if v_max is null then raise exception '활성 항목을 찾을 수 없습니다.'; end if;
  if v_scope = '계정당' then v_character := null; end if;
  v_period := (date_trunc(case when v_cycle = '일간' then 'day' else 'week' end, (now() at time zone 'Asia/Seoul') - interval '6 hours') + interval '6 hours') at time zone 'Asia/Seoul';
  return query insert into public.kronos_progress as old (account_id, character_name, kind, item_id, period_start, count, bookmarked)
    values (p_account, v_character, p_kind, p_item, v_period, greatest(0, least(v_max, p_delta)), coalesce(p_bookmarked, false))
    on conflict (account_id, target_key, kind, item_id) do update set
      count = greatest(0, least(v_max, (case when old.period_start = v_period then old.count else 0 end) + p_delta)),
      period_start = v_period, bookmarked = coalesce(p_bookmarked, old.bookmarked)
    returning *;
end;
$$;
revoke all on function public.sanctum_kronos_progress(uuid,text,text,bigint,integer,boolean) from public, anon, authenticated;
grant execute on function public.sanctum_kronos_progress(uuid,text,text,bigint,integer,boolean) to service_role;
comment on table public.kronos_reminders is 'Private two-slot character reminders; session-checked server API only.';
notify pgrst, 'reload schema';
commit;
